<a href="https://colab.research.google.com/github/vitoriapmaattos/dataanalytics/blob/main/Aula_1_Produ%C3%A7%C3%A3o_Hospitalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Analisando dados da saúde Hospitalar

Importar a biblioteca pandas:

In [37]:
import pandas as pd

Ler, higienizar arquivo e inserir os dados em uma variável: (criando um data frame)

In [ ]:
dados = pd.read_csv("/content/sih_cnv_qiuf22354845_166_204_25.csv", encoding="ISO-8859-1",  skiprows=3, sep=";", skipfooter=12, thousands=".", decimal=",")

> encoding = Define o padrãod e códigos do arquivo

> skiprows = Exclui as linhas iniciais do arquivo

> skipfooter = Exclui as linhas finais do arquivo

> sep = Define o separados do arquivo CSV

> thousands = Define a pontuação padrão para milheiros

> decimal = Define a pontuação padrão para decimais


Imprimir cabeçalho + 5 primeiras linhas

In [66]:
dados.head()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2023/Mai,2023/Jun,2023/Jul,2023/Ago,2023/Set,2023/Out,2023/Nov,2023/Dez,2024/Jan,Total
0,11 Rondônia,1388528.39,2931283.42,1541682.52,1525314.96,1645953.84,1406150.68,3065279.01,3231494.61,3117178.63,...,13767058.64,11273846.83,12443977.87,13054654.77,11274549.92,12082214.04,11392759.99,9603361.10,10516070.26,1394262146.50
1,12 Acre,902416.00,1497206.26,1794028.48,1730469.42,1819443.92,1828496.00,2511754.59,2089107.14,2275708.53,...,4845006.75,5124899.00,5692793.93,4561281.78,4019181.11,4150926.64,5712687.05,3503827.09,-,587778407.94
2,13 Amazonas,4735529.42,7118990.57,8196635.49,8259378.42,7831399.90,8477273.62,9368858.72,9352532.70,9363099.35,...,21710028.09,22198453.04,24809424.63,25005960.66,17522338.72,19613290.58,18387673.59,14265257.60,15065867.12,2613559191.21
3,14 Roraima,657889.53,777939.31,718688.03,839994.39,862347.96,832440.66,996693.09,894271.18,910424.17,...,4435042.77,3817361.58,4040988.99,4766375.31,1679849.33,2443674.72,2868626.39,2077360.03,2164371.02,451170144.15
4,15 Pará,18864744.11,19553758.20,21937342.70,20842829.69,23249952.88,23240687.56,24002223.56,23341218.03,25172261.32,...,46925899.02,45938305.83,54094884.03,50116544.12,51268388.79,50646320.52,55501176.43,54223823.56,43689467.84,6322687933.44

imprimir cabeçalho + 5 últimas linhas

In [67]:
dados.tail()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2023/Mai,2023/Jun,2023/Jul,2023/Ago,2023/Set,2023/Out,2023/Nov,2023/Dez,2024/Jan,Total
22,43 Rio Grande do Sul,30931325.46,57363420.01,51547794.07,56673338.49,48397733.07,52413429.62,56636376.98,56113054.70,55356224.30,...,112385822.04,113809028.30,116985178.63,120027121.08,116546657.80,122325557.64,114892531.95,114464874.02,120732038.67,16750147966.65
23,50 Mato Grosso do Sul,5377392.11,7002472.61,8423933.19,8797487.68,9770421.80,10905392.18,10249299.82,9671553.45,10218511.05,...,26973943.11,26354221.47,26569066.08,27768462.56,28200723.03,26783833.64,27456434.20,26922668.28,23959476.62,3219624366.70
24,51 Mato Grosso,4795299.01,8684882.23,7886243.14,8794109.79,9231645.40,10221763.77,9163314.28,9243148.81,9052354.89,...,23431985.13,24728541.29,24130933.81,22608901.38,23329871.28,22552033.63,22790096.76,19782985.94,21462469.97,2988456549.66
25,52 Goiás,15310637.29,22258668.68,21442515.75,20921212.45,21615970.67,18270043.87,20540517.13,20650730.67,20868443.56,...,50235627.95,44674462.22,53622374.91,51008354.28,49885683.22,50434366.44,47764974.85,50332961.30,47555420.60,6682627768.18
26,53 Distrito Federal,4745919.19,7632480.67,9647203.26,11098732.99,12891719.72,12850125.67,12565646.74,13710857.89,13165106.20,...,27495227.73,28258576.00,29034177.33,30961244.28,31610313.47,29140330.80,30810835.09,29465293.81,31878001.55,3543027009.96

Formatar números com 2 casas depois da virgula

In [70]:
pd.options.display.float_format = "{:.2f}".format

Média por mês de gastos

In [71]:
dados.mean(numeric_only=True)

2008/Jan     15126846.64
2008/Fev     22710158.12
2008/Mar     24594187.35
2008/Abr     25431957.83
2008/Mai     26511245.91
                ...
2023/Set     65189094.24
2023/Out     66941705.27
2023/Nov     65725826.24
2023/Dez     65537138.18
Total      8578342381.93
Length: 192, dtype: float64

In [73]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Columns: 195 entries, Unidade da Federação to Total
dtypes: float64(192), object(3)
memory usage: 41.3+ KB

#DESAFIO 1

Mostrar somente a coluna mais recente de todas.

In [80]:
dados.iloc[:,[0,-2]]

      Unidade da Federação      2024/Jan
0              11 Rondônia   10516070.26
1                  12 Acre             -
2              13 Amazonas   15065867.12
3               14 Roraima    2164371.02
4                  15 Pará   43689467.84
5                 16 Amapá    3961035.17
6             17 Tocantins     426805.38
7              21 Maranhão   37885708.46
8                 22 Piauí   20541206.34
9                 23 Ceará   61814810.50
10  24 Rio Grande do Norte   24197408.11
11              25 Paraíba   33490746.90
12           26 Pernambuco   84078535.80
13              27 Alagoas   20349028.62
14              28 Sergipe   16082837.55
15                29 Bahia   94641578.14
16         31 Minas Gerais  214852257.67
17       32 Espírito Santo   39634805.09
18       33 Rio de Janeiro  119869243.96
19            35 São Paulo  386813086.90
20               41 Paraná  155308686.22
21       42 Santa Catarina  101777599.24
22    43 Rio Grande do Sul  120732038.67
23   50 Mato Grosso do Sul   23959476.62
24          51 Mato Grosso   21462469.97
25                52 Goiás   47555420.60
26     53 Distrito Federal   31878001.55